name: build container image
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        registry:
          - ghcr.io
        flavor:
          - amd
          - cuda
          # - cloud
        include:
          - flavor: amd
            pip-requirements: requirements-lin-amd.txt
            dockerfile: docker-build/Dockerfile
            platforms: linux/amd64,linux/arm64
          - flavor: cuda
            pip-requirements: requirements-lin-cuda.txt
            dockerfile: docker-build/Dockerfile
            platforms: linux/amd64,linux/arm64
          # - flavor: cloud
          #   pip-requirements: requirements-lin-cuda.txt
          #   dockerfile: docker-build/Dockerfile.cloud
          #   platforms: linux/amd64
    runs-on: ubuntu-latest
    name: ${{ matrix.flavor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.registry }}/${{ github.repository }}-${{ matrix.flavor }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            latest=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - if: github.event_name != 'pull_request'
        name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: pip_requirements=${{ matrix.pip-requirements }}
